### ISSUE TITLE
Impossible de se connecté

### ISSUE THREAD

**Issue by DarkShoro** [MineWeb/Plugin-Auth#6]
Bonjour, j'ai beau suivre la doc a la lettre, je n'arrive pas a me connecté et le launcher me renvois cette erreur :

`fr.northenflo.auth.exception.DataWrongException: error_data
	at fr.northenflo.auth.mineweb.AuthMineweb.start(AuthMineweb.java:69)
	at cf.eradium.zenevaia.launcher.Launcher.auth(Launcher.java:32)
	at cf.eradium.zenevaia.launcher.LauncherFrame.main(LauncherFrame.java:6)
`

**Comment by Nawac** [comment]
Bonsoir, j'ai le même problème. La version de mon MineWeb est 1.13.0

**Comment by Loyto-SKHR** [comment]
Bonjour, je pense que t'on problème provient du fait que tu n'es pas en sha252 pour l'enregistrement du mot de passe.

**Comment by mifo77** [comment]
> Bonjour, je pense que t'on problème provient du fait que tu n'es pas en sha252 pour l'enregistrement du mot de passe.

et comment je fais pour remédier à ça ?

**Comment by Loyto-SKHR** [comment]
Pour changer la méthode de hachage, il faut aller dans les paramètres de MineWeb. Pour que le changement s'applique sur les comptes, il faudra se reconnecter sur chaque compte.

**Comment by MIFO77** [comment]
Les paramètres de mineweb sur le site ?

**Comment by MIFO77** [comment]
trouvé

**Comment by MIFO77** [comment]
> Bonjour, je pense que t'on problème provient du fait que tu n'es pas en sha252 pour l'enregistrement du mot de passe.
ok j'ai sha256 je met ?
sinon j'ai sha1, sha384, sha512

**Comment by mifo77** [comment]
Exception in thread "Thread-3" java.lang.IllegalArgumentException: authInfos == null
	at fr.theshark34.openlauncherlib.minecraft.MinecraftLauncher.createExternalProfile(MinecraftLauncher.java:122)
	at fr.gallinium.launcher.Launcher.launch(Launcher.java:76)
	at fr.gallinium.launcher.LauncherPanel.lambda$onEvent$0(LauncherPanel.java:126)
	at java.lang.Thread.run(Thread.java:750)
	
	

j'ai ça comme erreur mtn mdr

**Comment by Loyto-SKHR** [comment]
Sans code source, c'est compliqué mais est ce que tu as bien mis ta variable authinfos?

**Comment by mifo77** [comment]
private static AuthInfos authInfos;
    private static Thread updateThread;
[...]
public static void launch() throws LaunchException{

        ExternalLaunchProfile profile = MinecraftLauncher.createExternalProfile(GL_INFOS, GameFolder.BASIC, authInfos);
        profile.getVmArgs().addAll(Arrays.asList(LauncherFrame.getInstance().getLauncherPanel().getRamSelector().getRamArguments()));
        ExternalLauncher launcher = new ExternalLauncher(profile);


        Process p = launcher.launch();

        ProcessLogManager manager = new ProcessLogManager(p.getInputStream(), new File(GL_DIR, "logs.txt"));
        manager.start();


j'ajoute quoi dcp ?

**Comment by Loyto-SKHR** [comment]
C'est normal, ta variable authinfos est vide il faut que tu rajoute une ligne dans ton code dan ta phase de login:
`authInfos = new AuthInfos(username, "dry", "none");`

**Comment by mifo77** [comment]
juste en dessous du private static Authinfos authinfos; c'est ca ?

**Comment by MIFO77** [comment]
```private static AuthInfos authInfos;
    private static Thread updateThread;

    public static void auth(String username) {
        authInfos = new AuthInfos(username, "sry", "nope");
    }```

J'ai ajouté ça mais j'ai quand même une erreur au niveau du LauncherPanel:

```Thread t = new Thread() {
                @Override
                public void run() {
                    AuthMineweb.setTypeConnection(TypeConnection.launcher);
                    AuthMineweb.setUrlRoot("https://gallinium.ml");
                    AuthMineweb.setUsername(usernameField.getText());
                    AuthMineweb.setPassword(String.valueOf(passwordField.getPassword()));
                    try {
                        AuthMineweb.start();
                    } catch (DataWrongException | DataEmptyException | ServerNotFoundException | IOException f) {
                        f.printStackTrace();
                        return;
                    }
                    if(AuthMineweb.isConnected())
                    {
                        Thread h = new Thread() {
                            @Override
                            public void run()
                            {
                                try {
                                    Launcher.update();
                                } catch (Exception e1) {
                                    Launcher.interruptThread();
                                    Launcher.getCrashReporter().catchError(e1, "Impossible de mettre à jour");
                                    JOptionPane.showMessageDialog(LauncherPanel.this, "Erreur, Impossible de mettre le jeu à jour : " + e1 + "Erreur");
                                    setFieldsEnabled(true);
                                    return;
                                }

                                try {
                                    Launcher.launch();
                                } catch (LaunchException e1) {
                                    Launcher.getCrashReporter().catchError(e1, "Impossible de lancer le jeu");
                                }
                            }
                        };h.start();
                    }
                }

            };t.start();```

Et l'erreur c'est toujours authInfos == null:

```Exception in thread "Thread-4" java.lang.IllegalArgumentException: authInfos == null
	at fr.theshark34.openlauncherlib.minecraft.MinecraftLauncher.createExternalProfile(MinecraftLauncher.java:122)
	at fr.gallinium.launcher.Launcher.launch(Launcher.java:75)
	at fr.gallinium.launcher.LauncherPanel$1$1.run(LauncherPanel.java:135)```

**Comment by Loyto-SKHR** [comment]
Au début dans le `if(AuthMineweb.isConnected())`

**Comment by MIFO77** [comment]
if(AuthMineweb.isConnected(authInfos = new AuthInfos(username, "sry", "nope"))) ?

**Comment by MIFO77** [comment]
Heyy, je reviens ici parce que je n'arrive toujours pas à trouver le problème et je ne trouve aucun forum sur le problème, toujours la même erreur
